frequency: 35
sensor_timeout: 0.1
transform_time_offset: 0.1
two_d_mode: true
publish_tf: false
odom_frame: odom
base_link_frame: robot_footprint
world_frame: odom

odom0: /odom
odom0_config: [true, true, false,
               false, false, true,
               true, true, false,
               false, false, true,
               true, false, false]
odom0_differential: false

imu0: /imu/data
imu0_config: [false, false, false,
              false, false, true,
              false, false, false,
              false, false, true,
              true, false, false]
imu0_differential: false